# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e8d4f9b77c72cc7a07a6fd2204bca7488e65d47758712e2194c5d9a8341887f3bd836040f4f36b6703a766918f12126a665dcc7d71961771500944e4c433d68

test:
  secret_key_base: ee9911709d1a264a78702427ee55d556ea2433d791bbbd7a1189bf229fb9823d80185a1ee5f38b047b37a3fd07151a505c1a85ae5d6c8cdbf9e294fe96cb4ee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
